/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/_authenticated/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/historique' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/historique' | '/'
  id: '__root__' | '/_authenticated/historique' | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
